# config.yml

# === Backend ===
# Configure how the CMS connects to your Git repository
backend:
  name: git-gateway # Use Netlify's Git Gateway for authentication
  branch: main # Or master, or whichever branch Netlify builds from

# === Media ===
# Configure where images and files uploaded via the CMS are stored
media_folder: "images/uploads" # Path where files will be uploaded (relative to root)
public_folder: "/images/uploads" # Path used in generated content (e.g., ![alt](/images/uploads/image.jpg))

# === Collections ===
# Define the content types you want to edit
collections:
  # --- Example 1: Editing specific parts of the Homepage ---
  - name: "pages" # Can be anything descriptive
    label: "Pages"
    files: # Used for single files (like settings or specific pages)
      - label: "Homepage"
        name: "homepage"
        file: "_data/homepage.yml" # Path to a DATA file (YAML or JSON) to store homepage content
        fields: # Define the editable fields
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Hero Button Text", name: "hero_button_text", widget: "string" }
          - { label: "Hero Button Link", name: "hero_button_link", widget: "string" }
          # Add fields for quick info sections, etc.

  # --- Example 2: Editing News Items (assuming they might become Markdown files) ---
  - name: "news"
    label: "News"
    folder: "nieuws" # Folder where news articles will be stored (e.g., /nieuws/my-first-post.md)
    create: true # Allow creating new news items
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # How filename is generated
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" } # The main content

  # --- Example 3: Editing Footer Content (if dynamic) ---
  # - name: "settings"
  #   label: "Site Settings"
  #   files:
  #     - label: "Footer"
  #       name: "footer"
  #       file: "_data/footer.yml"
  #       fields:
  #         - { label: "Copyright Text", name: "copyright", widget: "string" }
  #         - { label: "Footer Links Column 1 Title", name: "col1_title", widget: "string"}
  #         - { label: "Footer Links Column 1", name: "col1_links", widget: "list", fields: [
  #             { label: "Text", name: "text", widget: "string" },
  #             { label: "URL", name: "url", widget: "string" }
  #           ]}
          # Add more columns as needed